### ISSUE TITLE
翻译认领/TSH Frontend Report

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/Annual-Survey#4]
@lsvih 认领一下 TSH Frontend Report 的翻译～

**Comment by lsvih** [comment]
本文翻译：PassionPenguin 
校对：Usualminds HumanBeingXenon

**Comment by PassionPenguin** [comment]
@lsvih @Usualminds @HumanBeingXenon 之前一直在等 tsh.io 的消息，应该算是官方授权或是官方知晓的了

[「回顾 2020」前端状况调查报告 —— 目录](https://juejin.cn/post/6936120097631109128)
[「回顾 2020」前端状态调查报告 —— 开发者 与 框架](https://juejin.cn/post/6936122892513984542)
[「回顾 2020」前端状态调查报告 —— 托管 与 JavaScript API Markup](https://juejin.cn/post/6936122418041716766)
[「回顾 2020」前端状态调查报告 —— 微前端 和 搜索引擎优化](https://juejin.cn/post/6936122350379204615)
[「回顾 2020」前端状态调查报告 —— 应用程序无障碍功能 和 开发团队](https://juejin.cn/post/6936122530197405710)
[「回顾 2020」前端状态调查报告 —— 设计 和 QA](https://juejin.cn/post/6936122882041446430)
[「回顾 2020」前端状态调查报告 —— 前端的未来](https://juejin.cn/post/6936121598566989837)
