### ISSUE TITLE
翻译认领/MDN DNA 2019

### ISSUE THREAD

**Issue by PassionPenguin** [xitu/Annual-Survey#8]
翻译认领/MDN DNA 2019 ψ(｀∇´)ψ
<img width="258" alt="Screen Shot 2021-02-04 at 3 00 07 PM" src="https://user-images.githubusercontent.com/41184947/106856605-b38a3080-66f9-11eb-933e-0408ef122319.png">

- [x] Introduction
- [x] Study Participants
- [x] Needs Assessment
- [x] Overall Satisfaction With the Web
- [x] What’s Missing From the Web
- [x] Technologies
- [x] Pilot Interview Findings
- [x] Conclusion
- [x] Methodology

 @lsvih

**Comment by PassionPenguin** [comment]
= = 还剩 72706 个字符 = =

**Comment by lsvih** [comment]
慢慢来啊
